// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using XpLevelCalculator.Core.DataAccess;

#nullable disable

namespace XpLevelCalculator.Core.Migrations
{
    [DbContext(typeof(XpCalculatorDbContext))]
    partial class XpCalculatorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("XpLevelCalculator.Core.Models.LevelModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<long>("LevelXp")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalXp")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Levels");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Level = 1,
                            LevelXp = 0L,
                            TotalXp = 0L
                        },
                        new
                        {
                            Id = 2L,
                            Level = 2,
                            LevelXp = 300L,
                            TotalXp = 300L
                        },
                        new
                        {
                            Id = 3L,
                            Level = 3,
                            LevelXp = 450L,
                            TotalXp = 750L
                        },
                        new
                        {
                            Id = 4L,
                            Level = 4,
                            LevelXp = 630L,
                            TotalXp = 1380L
                        },
                        new
                        {
                            Id = 5L,
                            Level = 5,
                            LevelXp = 970L,
                            TotalXp = 2350L
                        },
                        new
                        {
                            Id = 6L,
                            Level = 6,
                            LevelXp = 1440L,
                            TotalXp = 3790L
                        },
                        new
                        {
                            Id = 7L,
                            Level = 7,
                            LevelXp = 1940L,
                            TotalXp = 5730L
                        },
                        new
                        {
                            Id = 8L,
                            Level = 8,
                            LevelXp = 3000L,
                            TotalXp = 8730L
                        },
                        new
                        {
                            Id = 9L,
                            Level = 9,
                            LevelXp = 3920L,
                            TotalXp = 12650L
                        },
                        new
                        {
                            Id = 10L,
                            Level = 10,
                            LevelXp = 4970L,
                            TotalXp = 17620L
                        },
                        new
                        {
                            Id = 11L,
                            Level = 11,
                            LevelXp = 5900L,
                            TotalXp = 23520L
                        },
                        new
                        {
                            Id = 12L,
                            Level = 12,
                            LevelXp = 7430L,
                            TotalXp = 30950L
                        },
                        new
                        {
                            Id = 13L,
                            Level = 13,
                            LevelXp = 8620L,
                            TotalXp = 39570L
                        },
                        new
                        {
                            Id = 14L,
                            Level = 14,
                            LevelXp = 10200L,
                            TotalXp = 49770L
                        },
                        new
                        {
                            Id = 15L,
                            Level = 15,
                            LevelXp = 11300L,
                            TotalXp = 61070L
                        },
                        new
                        {
                            Id = 16L,
                            Level = 16,
                            LevelXp = 13100L,
                            TotalXp = 74170L
                        },
                        new
                        {
                            Id = 17L,
                            Level = 17,
                            LevelXp = 15200L,
                            TotalXp = 89370L
                        },
                        new
                        {
                            Id = 18L,
                            Level = 18,
                            LevelXp = 17400L,
                            TotalXp = 106770L
                        },
                        new
                        {
                            Id = 19L,
                            Level = 19,
                            LevelXp = 19600L,
                            TotalXp = 126370L
                        },
                        new
                        {
                            Id = 20L,
                            Level = 20,
                            LevelXp = 21900L,
                            TotalXp = 148270L
                        },
                        new
                        {
                            Id = 21L,
                            Level = 21,
                            LevelXp = 24300L,
                            TotalXp = 172570L
                        },
                        new
                        {
                            Id = 22L,
                            Level = 22,
                            LevelXp = 27400L,
                            TotalXp = 199970L
                        },
                        new
                        {
                            Id = 23L,
                            Level = 23,
                            LevelXp = 30600L,
                            TotalXp = 230750L
                        },
                        new
                        {
                            Id = 24L,
                            Level = 24,
                            LevelXp = 33900L,
                            TotalXp = 264470L
                        },
                        new
                        {
                            Id = 25L,
                            Level = 25,
                            LevelXp = 37300L,
                            TotalXp = 301770L
                        },
                        new
                        {
                            Id = 26L,
                            Level = 26,
                            LevelXp = 40800L,
                            TotalXp = 342570L
                        },
                        new
                        {
                            Id = 27L,
                            Level = 27,
                            LevelXp = 49200L,
                            TotalXp = 391770L
                        },
                        new
                        {
                            Id = 28L,
                            Level = 28,
                            LevelXp = 54600L,
                            TotalXp = 446370L
                        },
                        new
                        {
                            Id = 29L,
                            Level = 29,
                            LevelXp = 61900L,
                            TotalXp = 508270L
                        },
                        new
                        {
                            Id = 30L,
                            Level = 30,
                            LevelXp = 65600L,
                            TotalXp = 573870L
                        },
                        new
                        {
                            Id = 31L,
                            Level = 31,
                            LevelXp = 68400L,
                            TotalXp = 642270L
                        },
                        new
                        {
                            Id = 32L,
                            Level = 32,
                            LevelXp = 74000L,
                            TotalXp = 716270L
                        },
                        new
                        {
                            Id = 33L,
                            Level = 33,
                            LevelXp = 82700L,
                            TotalXp = 798970L
                        },
                        new
                        {
                            Id = 34L,
                            Level = 34,
                            LevelXp = 88700L,
                            TotalXp = 887670L
                        },
                        new
                        {
                            Id = 35L,
                            Level = 35,
                            LevelXp = 95000L,
                            TotalXp = 982670L
                        },
                        new
                        {
                            Id = 36L,
                            Level = 36,
                            LevelXp = 102000L,
                            TotalXp = 1084670L
                        },
                        new
                        {
                            Id = 37L,
                            Level = 37,
                            LevelXp = 113000L,
                            TotalXp = 1197670L
                        },
                        new
                        {
                            Id = 38L,
                            Level = 38,
                            LevelXp = 121000L,
                            TotalXp = 1318670L
                        },
                        new
                        {
                            Id = 39L,
                            Level = 39,
                            LevelXp = 133000L,
                            TotalXp = 1451670L
                        },
                        new
                        {
                            Id = 40L,
                            Level = 40,
                            LevelXp = 142000L,
                            TotalXp = 1593670L
                        },
                        new
                        {
                            Id = 41L,
                            Level = 41,
                            LevelXp = 155000L,
                            TotalXp = 1748670L
                        },
                        new
                        {
                            Id = 42L,
                            Level = 42,
                            LevelXp = 163000L,
                            TotalXp = 1911670L
                        },
                        new
                        {
                            Id = 43L,
                            Level = 43,
                            LevelXp = 171000L,
                            TotalXp = 2082670L
                        },
                        new
                        {
                            Id = 44L,
                            Level = 44,
                            LevelXp = 179000L,
                            TotalXp = 2261670L
                        },
                        new
                        {
                            Id = 45L,
                            Level = 45,
                            LevelXp = 187000L,
                            TotalXp = 2448670L
                        },
                        new
                        {
                            Id = 46L,
                            Level = 46,
                            LevelXp = 195000L,
                            TotalXp = 2643670L
                        },
                        new
                        {
                            Id = 47L,
                            Level = 47,
                            LevelXp = 214000L,
                            TotalXp = 2857670L
                        },
                        new
                        {
                            Id = 48L,
                            Level = 48,
                            LevelXp = 229000L,
                            TotalXp = 3086670L
                        },
                        new
                        {
                            Id = 49L,
                            Level = 49,
                            LevelXp = 244000L,
                            TotalXp = 3330670L
                        },
                        new
                        {
                            Id = 50L,
                            Level = 50,
                            LevelXp = 259000L,
                            TotalXp = 3589670L
                        },
                        new
                        {
                            Id = 51L,
                            Level = 51,
                            LevelXp = 421000L,
                            TotalXp = 4010670L
                        },
                        new
                        {
                            Id = 52L,
                            Level = 52,
                            LevelXp = 500000L,
                            TotalXp = 4510670L
                        },
                        new
                        {
                            Id = 53L,
                            Level = 53,
                            LevelXp = 580000L,
                            TotalXp = 5090670L
                        },
                        new
                        {
                            Id = 54L,
                            Level = 54,
                            LevelXp = 663000L,
                            TotalXp = 5753670L
                        },
                        new
                        {
                            Id = 55L,
                            Level = 55,
                            LevelXp = 749000L,
                            TotalXp = 6502670L
                        },
                        new
                        {
                            Id = 56L,
                            Level = 56,
                            LevelXp = 837000L,
                            TotalXp = 7339670L
                        },
                        new
                        {
                            Id = 57L,
                            Level = 57,
                            LevelXp = 927000L,
                            TotalXp = 8266670L
                        },
                        new
                        {
                            Id = 58L,
                            Level = 58,
                            LevelXp = 1019000L,
                            TotalXp = 9285670L
                        },
                        new
                        {
                            Id = 59L,
                            Level = 59,
                            LevelXp = 1114000L,
                            TotalXp = 10399670L
                        },
                        new
                        {
                            Id = 60L,
                            Level = 60,
                            LevelXp = 1211000L,
                            TotalXp = 11610670L
                        },
                        new
                        {
                            Id = 61L,
                            Level = 61,
                            LevelXp = 1387000L,
                            TotalXp = 12997670L
                        },
                        new
                        {
                            Id = 62L,
                            Level = 62,
                            LevelXp = 1456000L,
                            TotalXp = 14453670L
                        },
                        new
                        {
                            Id = 63L,
                            Level = 63,
                            LevelXp = 1534000L,
                            TotalXp = 15987670L
                        },
                        new
                        {
                            Id = 64L,
                            Level = 64,
                            LevelXp = 1621000L,
                            TotalXp = 17608670L
                        },
                        new
                        {
                            Id = 65L,
                            Level = 65,
                            LevelXp = 1720000L,
                            TotalXp = 19328670L
                        },
                        new
                        {
                            Id = 66L,
                            Level = 66,
                            LevelXp = 1834000L,
                            TotalXp = 21162670L
                        },
                        new
                        {
                            Id = 67L,
                            Level = 67,
                            LevelXp = 1968000L,
                            TotalXp = 23130670L
                        },
                        new
                        {
                            Id = 68L,
                            Level = 68,
                            LevelXp = 2126000L,
                            TotalXp = 25256670L
                        },
                        new
                        {
                            Id = 69L,
                            Level = 69,
                            LevelXp = 2137000L,
                            TotalXp = 27393670L
                        },
                        new
                        {
                            Id = 70L,
                            Level = 70,
                            LevelXp = 2550000L,
                            TotalXp = 29943670L
                        },
                        new
                        {
                            Id = 71L,
                            Level = 71,
                            LevelXp = 2923000L,
                            TotalXp = 32866670L
                        },
                        new
                        {
                            Id = 72L,
                            Level = 72,
                            LevelXp = 3018000L,
                            TotalXp = 35884670L
                        },
                        new
                        {
                            Id = 73L,
                            Level = 73,
                            LevelXp = 3153000L,
                            TotalXp = 39037670L
                        },
                        new
                        {
                            Id = 74L,
                            Level = 74,
                            LevelXp = 3324000L,
                            TotalXp = 42361670L
                        },
                        new
                        {
                            Id = 75L,
                            Level = 75,
                            LevelXp = 3532000L,
                            TotalXp = 45893670L
                        },
                        new
                        {
                            Id = 76L,
                            Level = 76,
                            LevelXp = 3770600L,
                            TotalXp = 49664270L
                        },
                        new
                        {
                            Id = 77L,
                            Level = 77,
                            LevelXp = 4066000L,
                            TotalXp = 53730270L
                        },
                        new
                        {
                            Id = 78L,
                            Level = 78,
                            LevelXp = 4377000L,
                            TotalXp = 58107270L
                        },
                        new
                        {
                            Id = 79L,
                            Level = 79,
                            LevelXp = 4777000L,
                            TotalXp = 62884270L
                        },
                        new
                        {
                            Id = 80L,
                            Level = 80,
                            LevelXp = 5256000L,
                            TotalXp = 68140270L
                        },
                        new
                        {
                            Id = 81L,
                            Level = 81,
                            LevelXp = 5992000L,
                            TotalXp = 74132270L
                        },
                        new
                        {
                            Id = 82L,
                            Level = 82,
                            LevelXp = 6171700L,
                            TotalXp = 80303270L
                        },
                        new
                        {
                            Id = 83L,
                            Level = 83,
                            LevelXp = 6942000L,
                            TotalXp = 87245270L
                        },
                        new
                        {
                            Id = 84L,
                            Level = 84,
                            LevelXp = 7205000L,
                            TotalXp = 94450270L
                        },
                        new
                        {
                            Id = 85L,
                            Level = 85,
                            LevelXp = 7948000L,
                            TotalXp = 102398270L
                        },
                        new
                        {
                            Id = 86L,
                            Level = 86,
                            LevelXp = 8287000L,
                            TotalXp = 110685270L
                        },
                        new
                        {
                            Id = 87L,
                            Level = 87,
                            LevelXp = 9231000L,
                            TotalXp = 119916270L
                        },
                        new
                        {
                            Id = 88L,
                            Level = 88,
                            LevelXp = 9529000L,
                            TotalXp = 129445270L
                        },
                        new
                        {
                            Id = 89L,
                            Level = 89,
                            LevelXp = 10459000L,
                            TotalXp = 139904270L
                        },
                        new
                        {
                            Id = 90L,
                            Level = 90,
                            LevelXp = 10838000L,
                            TotalXp = 150742270L
                        },
                        new
                        {
                            Id = 91L,
                            Level = 91,
                            LevelXp = 13278000L,
                            TotalXp = 164020270L
                        },
                        new
                        {
                            Id = 92L,
                            Level = 92,
                            LevelXp = 13659000L,
                            TotalXp = 177679270L
                        },
                        new
                        {
                            Id = 93L,
                            Level = 93,
                            LevelXp = 15348000L,
                            TotalXp = 193027270L
                        },
                        new
                        {
                            Id = 94L,
                            Level = 94,
                            LevelXp = 15912000L,
                            TotalXp = 208939270L
                        },
                        new
                        {
                            Id = 95L,
                            Level = 95,
                            LevelXp = 17534000L,
                            TotalXp = 226437270L
                        },
                        new
                        {
                            Id = 96L,
                            Level = 96,
                            LevelXp = 18263000L,
                            TotalXp = 244736270L
                        },
                        new
                        {
                            Id = 97L,
                            Level = 97,
                            LevelXp = 20322000L,
                            TotalXp = 265058270L
                        },
                        new
                        {
                            Id = 98L,
                            Level = 98,
                            LevelXp = 20957000L,
                            TotalXp = 286015270L
                        },
                        new
                        {
                            Id = 99L,
                            Level = 99,
                            LevelXp = 22979000L,
                            TotalXp = 308994270L
                        },
                        new
                        {
                            Id = 100L,
                            Level = 100,
                            LevelXp = 23789000L,
                            TotalXp = 332783270L
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
